name = "Quizcast"
license = "MIT"
licenselink = "https://github.com/ObjectBoxPC/quizcast/blob/master/LICENSE.txt"
description = "Theme for creating quiz slideshows using Slidy2"
homepage = "http://github.com/ObjectBoxPC/quizcast"
tags = ["quiz", "slideshow"]
features = []
min_version = "0.48"

[author]
name = "Philip Chung"
homepage = "http://objectboxpc.name/"
